// Code generated by Kitex v0.12.3. DO NOT EDIT.

package seckillservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	seckill "kitex-server/seckill/kitex_gen/seckill"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SecKill(ctx context.Context, req *seckill.SecKillRequest, callOptions ...callopt.Option) (r *seckill.SecKillResponse, err error)
	CreateSecKill(ctx context.Context, req *seckill.CreateSecKillRequest, callOptions ...callopt.Option) (r *seckill.CreateSecKillResponse, err error)
	GetOrderStatus(ctx context.Context, req *seckill.GetOrderStatusRequest, callOptions ...callopt.Option) (r *seckill.GetOrderStatusResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSecKillServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSecKillServiceClient struct {
	*kClient
}

func (p *kSecKillServiceClient) SecKill(ctx context.Context, req *seckill.SecKillRequest, callOptions ...callopt.Option) (r *seckill.SecKillResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SecKill(ctx, req)
}

func (p *kSecKillServiceClient) CreateSecKill(ctx context.Context, req *seckill.CreateSecKillRequest, callOptions ...callopt.Option) (r *seckill.CreateSecKillResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateSecKill(ctx, req)
}

func (p *kSecKillServiceClient) GetOrderStatus(ctx context.Context, req *seckill.GetOrderStatusRequest, callOptions ...callopt.Option) (r *seckill.GetOrderStatusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrderStatus(ctx, req)
}
