// Code generated by Kitex v0.12.3. DO NOT EDIT.
package seckillservice

import (
	server "github.com/cloudwego/kitex/server"
	seckill "kitex-server/seckill/kitex_gen/seckill"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler seckill.SecKillService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler seckill.SecKillService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
