// Code generated by Kitex v0.12.3. DO NOT EDIT.

package itemservice

import (
	items "client/kitex-gens/items/kitex_gen/items"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetItemInfo(ctx context.Context, req *items.GetItemInfoRequest, callOptions ...callopt.Option) (r *items.GetItemInfoResponse, err error)
	GetItemList(ctx context.Context, req *items.GetItemListRequest, callOptions ...callopt.Option) (r *items.GetItemListResponse, err error)
	AddItem(ctx context.Context, req *items.AddItemRequest, callOptions ...callopt.Option) (r *items.AddItemResponse, err error)
	UpdateItem(ctx context.Context, req *items.UpdateItemRequest, callOptions ...callopt.Option) (r *items.UpdateItemResponse, err error)
	DeleteItem(ctx context.Context, req *items.DeleteItemRequest, callOptions ...callopt.Option) (r *items.DeleteItemResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kItemServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kItemServiceClient struct {
	*kClient
}

func (p *kItemServiceClient) GetItemInfo(ctx context.Context, req *items.GetItemInfoRequest, callOptions ...callopt.Option) (r *items.GetItemInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItemInfo(ctx, req)
}

func (p *kItemServiceClient) GetItemList(ctx context.Context, req *items.GetItemListRequest, callOptions ...callopt.Option) (r *items.GetItemListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetItemList(ctx, req)
}

func (p *kItemServiceClient) AddItem(ctx context.Context, req *items.AddItemRequest, callOptions ...callopt.Option) (r *items.AddItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddItem(ctx, req)
}

func (p *kItemServiceClient) UpdateItem(ctx context.Context, req *items.UpdateItemRequest, callOptions ...callopt.Option) (r *items.UpdateItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateItem(ctx, req)
}

func (p *kItemServiceClient) DeleteItem(ctx context.Context, req *items.DeleteItemRequest, callOptions ...callopt.Option) (r *items.DeleteItemResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteItem(ctx, req)
}
